### ISSUE TITLE
not working in any arch 64 and 32bit even i tired to run with admin

### ISSUE THREAD

**Issue by allowdoc** [gsmith257-cyber/BB-UACBypass-Loader#1]
Exception calling "Load" with "1" argument(s): "Could not load file or assembly '0 bytes loaded from Anonymously
Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An
attempt was made to load a program with an incorrect format."
At C:\Users\Administrator\Downloads\BB-UACBypass-Loader-main (1)\BB-UACBypass-Loader-main\installer.ps1:25 char:1
+ [Reflection.Assembly]::Load([Convert]::FromBase64String($base64String

**Comment by gsmith257-cyber** [comment]
This is meant to be executed form a Bash Bunny, not your Downloads. You would have to manually modify how it's executed to work from your Downloads.

**Comment by allowdoc** [comment]
how tell me i also change the directory location from download to my D disk not working even if if i tried to directly copy and paste the script into terminal not working so tell me actually not only this issue there is full issue.
Exception calling "ReadAllBytes" with "1" argument(s): "The network path was not found.
"
At C:\Users\Administrator\Downloads\BB-UACBypass-Loader-main
(1)\BB-UACBypass-Loader-main\installer.ps1:11 char:1
+ $encryptedBytes = [System.IO.File]::ReadAllBytes($dllPath)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IOException

Exception calling "TransformBlock" with "5" argument(s): "Value cannot be null.
Parameter name: inputBuffer"
At C:\Users\Administrator\Downloads\BB-UACBypass-Loader-main
(1)\BB-UACBypass-Loader-main\installer.ps1:20 char:1
+ $transform.TransformBlock($encryptedBytes, 0, $encryptedBytes.Length, ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

Exception calling "Load" with "1" argument(s): "Could not load file or assembly '0 bytes loaded
from Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral,
PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an
incorrect format."
At C:\Users\Administrator\Downloads\BB-UACBypass-Loader-main
(1)\BB-UACBypass-Loader-main\installer.ps1:25 char:1
+ [Reflection.Assembly]::Load([Convert]::FromBase64String($base64String ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : BadImageFormatException

Unable to find type [installer].
At C:\Users\Administrator\Downloads\BB-UACBypass-Loader-main
(1)\BB-UACBypass-Loader-main\installer.ps1:27 char:1
+ [installer]::Execute("$path2")
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (installer:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
    
![image](https://github.com/gsmith257-cyber/BB-UACBypass-Loader/assets/122750347/eb8d6704-f972-4727-a3f9-4121af1b68b4)
